// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst_n,0,0);
        VL_IN8(cfg_enable,0,0);
        VL_IN8(cfg_auto_repeat,0,0);
        VL_OUT8(ppu_ready,0,0);
        VL_OUT8(ppu_busy,0,0);
        VL_IN8(tile_start,0,0);
        VL_OUT8(tile_done,0,0);
        VL_IN8(tile_mem_addr,7,0);
        VL_IN8(tile_mem_wr_en,0,0);
        VL_IN8(pc_mem_addr,7,0);
        VL_IN8(pc_mem_data_in,7,0);
        VL_OUT8(pc_mem_data_out,7,0);
        VL_IN8(pc_mem_wr_en,0,0);
        VL_OUT8(task_valid,0,0);
        VL_OUT8(task_row_id,7,0);
        VL_OUT8(task_prefix_id,7,0);
        VL_OUT8(weight_addr,3,0);
        VL_OUT8(weight_rd_en,0,0);
        VL_OUT8(output_rd_addr,7,0);
        VL_OUT8(output_wr_addr,7,0);
        VL_OUT8(output_wr_en,0,0);
        VL_OUT8(dbg_state,3,0);
        VL_OUT8(dbg_det_ready,0,0);
        VL_OUT8(dbg_prn_ready,0,0);
        VL_OUT8(dbg_dsp_ready,0,0);
        VL_OUT8(dbg_proc_busy,0,0);
        VL_OUT8(core_ready,0,0);
        CData/*0:0*/ top__DOT__clk;
        CData/*0:0*/ top__DOT__rst_n;
        CData/*0:0*/ top__DOT__cfg_enable;
        CData/*0:0*/ top__DOT__cfg_auto_repeat;
        CData/*0:0*/ top__DOT__ppu_ready;
        CData/*0:0*/ top__DOT__ppu_busy;
        CData/*0:0*/ top__DOT__tile_start;
        CData/*0:0*/ top__DOT__tile_done;
        CData/*7:0*/ top__DOT__tile_mem_addr;
        CData/*0:0*/ top__DOT__tile_mem_wr_en;
        CData/*7:0*/ top__DOT__pc_mem_addr;
        CData/*7:0*/ top__DOT__pc_mem_data_in;
        CData/*7:0*/ top__DOT__pc_mem_data_out;
        CData/*0:0*/ top__DOT__pc_mem_wr_en;
        CData/*0:0*/ top__DOT__task_valid;
        CData/*7:0*/ top__DOT__task_row_id;
        CData/*7:0*/ top__DOT__task_prefix_id;
        CData/*3:0*/ top__DOT__weight_addr;
        CData/*0:0*/ top__DOT__weight_rd_en;
        CData/*7:0*/ top__DOT__output_rd_addr;
        CData/*7:0*/ top__DOT__output_wr_addr;
        CData/*0:0*/ top__DOT__output_wr_en;
        CData/*3:0*/ top__DOT__dbg_state;
        CData/*0:0*/ top__DOT__dbg_det_ready;
        CData/*0:0*/ top__DOT__dbg_prn_ready;
        CData/*0:0*/ top__DOT__dbg_dsp_ready;
        CData/*0:0*/ top__DOT__dbg_proc_busy;
        CData/*0:0*/ top__DOT__core_ready;
        CData/*2:0*/ top__DOT__state;
        CData/*2:0*/ top__DOT__next_state;
        CData/*7:0*/ top__DOT__row_counter;
        CData/*0:0*/ top__DOT__processing_done;
        CData/*0:0*/ top__DOT__det_q_ready;
        CData/*0:0*/ top__DOT__det_si_valid;
        CData/*0:0*/ top__DOT__det_done_flag;
        CData/*7:0*/ top__DOT__det_row_pc;
    };
    struct {
        CData/*0:0*/ top__DOT__detector_init_done;
        CData/*0:0*/ top__DOT____Vcellinp__u_detector__q_valid;
        CData/*0:0*/ top__DOT__prn_ready;
        CData/*0:0*/ top__DOT__prn_valid;
        CData/*7:0*/ top__DOT__prn_popcnt;
        CData/*0:0*/ top__DOT__row_done;
        CData/*0:0*/ top__DOT__ready_for_new_row;
        CData/*0:0*/ top__DOT__prune_done;
        CData/*7:0*/ top__DOT__prn_row_id;
        CData/*7:0*/ top__DOT__prn_prefix_id;
        CData/*0:0*/ top__DOT____Vcellinp__u_pruner__mem_wr_en;
        CData/*7:0*/ top__DOT____Vcellinp__u_pruner__mem_NO_in;
        CData/*7:0*/ top__DOT____Vcellinp__u_pruner__mem_addr;
        CData/*0:0*/ top__DOT__dsp_ready;
        CData/*0:0*/ top__DOT__dsp_tile_done;
        CData/*7:0*/ top__DOT__row_idx_r;
        CData/*7:0*/ top__DOT__prefix_id_r;
        CData/*7:0*/ top__DOT__row_popcnt_r;
        CData/*0:0*/ top__DOT__prn_valid_r;
        CData/*7:0*/ top__DOT__best_prefix;
        CData/*7:0*/ top__DOT__output_popcount;
        CData/*0:0*/ top__DOT__proc_ready;
        CData/*0:0*/ top__DOT__proc_busy;
        CData/*0:0*/ top__DOT__proc_done;
        CData/*0:0*/ top__DOT__u_detector__DOT__clk;
        CData/*0:0*/ top__DOT__u_detector__DOT__rst;
        CData/*0:0*/ top__DOT__u_detector__DOT__q_valid;
        CData/*0:0*/ top__DOT__u_detector__DOT__q_ready;
        CData/*0:0*/ top__DOT__u_detector__DOT__si_valid;
        CData/*0:0*/ top__DOT__u_detector__DOT__det_done;
        CData/*7:0*/ top__DOT__u_detector__DOT__row_idx;
        CData/*7:0*/ top__DOT__u_detector__DOT__row_popcnt;
        CData/*0:0*/ top__DOT__u_detector__DOT__detector_init_done;
        CData/*7:0*/ top__DOT__u_detector__DOT__tile_mem_addr;
        CData/*0:0*/ top__DOT__u_detector__DOT__tile_mem_wr_en;
        CData/*7:0*/ top__DOT__u_detector__DOT__popcount_mem_addr;
        CData/*7:0*/ top__DOT__u_detector__DOT__popcount_mem_data_in;
        CData/*0:0*/ top__DOT__u_detector__DOT__popcount_mem_wr_en;
        CData/*0:0*/ top__DOT__u_detector__DOT__popcounts_calculated;
        CData/*1:0*/ top__DOT__u_detector__DOT__state;
        CData/*1:0*/ top__DOT__u_detector__DOT__next_state;
        CData/*7:0*/ top__DOT__u_detector__DOT__load_counter;
        CData/*7:0*/ top__DOT__u_detector__DOT__popcount_counter;
        CData/*0:0*/ top__DOT__u_detector__DOT__initialized;
        CData/*0:0*/ top__DOT__u_detector__DOT__query_in_progress;
        CData/*7:0*/ top__DOT__u_detector__DOT__tcam_addr;
        CData/*0:0*/ top__DOT__u_detector__DOT__tcam_set_valid;
        CData/*0:0*/ top__DOT__u_detector__DOT__tcam_set_clr;
        CData/*0:0*/ top__DOT__u_detector__DOT__tcam_req_valid;
        CData/*7:0*/ top__DOT__u_detector__DOT__popcount_mem_data_out;
        CData/*0:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__clk;
        CData/*0:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__rst;
        CData/*7:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__set_addr;
        CData/*0:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__set_clr;
        CData/*0:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__set_valid;
        CData/*0:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__req_valid;
        CData/*0:0*/ top__DOT__u_pruner__DOT__clk;
        CData/*0:0*/ top__DOT__u_pruner__DOT__rst_n;
        CData/*7:0*/ top__DOT__u_pruner__DOT__row_index;
        CData/*7:0*/ top__DOT__u_pruner__DOT__row_NO;
        CData/*0:0*/ top__DOT__u_pruner__DOT__si_valid;
        CData/*0:0*/ top__DOT__u_pruner__DOT__pruner_ready;
        CData/*7:0*/ top__DOT__u_pruner__DOT__prefix_id;
        CData/*7:0*/ top__DOT__u_pruner__DOT__row_id_out;
    };
    struct {
        CData/*0:0*/ top__DOT__u_pruner__DOT__prune_valid;
        CData/*0:0*/ top__DOT__u_pruner__DOT__prune_done;
        CData/*0:0*/ top__DOT__u_pruner__DOT__dispatch_ready;
        CData/*7:0*/ top__DOT__u_pruner__DOT__mem_addr;
        CData/*7:0*/ top__DOT__u_pruner__DOT__mem_NO_in;
        CData/*7:0*/ top__DOT__u_pruner__DOT__mem_NO_out;
        CData/*0:0*/ top__DOT__u_pruner__DOT__mem_wr_en;
        CData/*0:0*/ top__DOT__u_pruner__DOT__mem_sel;
        CData/*2:0*/ top__DOT__u_pruner__DOT__state;
        CData/*7:0*/ top__DOT__u_pruner__DOT__row_idx_r;
        CData/*7:0*/ top__DOT__u_pruner__DOT__row_NO_r;
        CData/*7:0*/ top__DOT__u_pruner__DOT__best_idx_r;
        CData/*7:0*/ top__DOT__u_pruner__DOT__best_NO_r;
        CData/*7:0*/ top__DOT__u_pruner__DOT__st0_row_idx;
        CData/*7:0*/ top__DOT__u_pruner__DOT__st1_row_idx;
        CData/*7:0*/ top__DOT__u_pruner__DOT__st2_row_idx;
        CData/*7:0*/ top__DOT__u_pruner__DOT__st0_row_NO;
        CData/*7:0*/ top__DOT__u_pruner__DOT__st1_prefix_idx;
        CData/*7:0*/ top__DOT__u_pruner__DOT__st2_prefix_idx;
        CData/*0:0*/ top__DOT__u_pruner__DOT__st0_valid;
        CData/*0:0*/ top__DOT__u_pruner__DOT__st1_valid;
        CData/*0:0*/ top__DOT__u_pruner__DOT__st2_valid;
        CData/*7:0*/ top__DOT__u_pruner__DOT__best_idx_comb;
        CData/*7:0*/ top__DOT__u_pruner__DOT__best_no_comb;
        CData/*7:0*/ top__DOT__u_pruner__DOT____VdfgBinToOneHot_Pre_he920b6b0_0_0;
        CData/*0:0*/ top__DOT__u_dispatcher__DOT__clk;
        CData/*0:0*/ top__DOT__u_dispatcher__DOT__rst_n;
        CData/*0:0*/ top__DOT__u_dispatcher__DOT__row_info_valid;
        CData/*0:0*/ top__DOT__u_dispatcher__DOT__row_info_ready;
        CData/*7:0*/ top__DOT__u_dispatcher__DOT__row_idx;
        CData/*7:0*/ top__DOT__u_dispatcher__DOT__row_prefix_id;
        CData/*7:0*/ top__DOT__u_dispatcher__DOT__row_popcnt;
        CData/*0:0*/ top__DOT__u_dispatcher__DOT__row_last;
        CData/*0:0*/ top__DOT__u_dispatcher__DOT__proc_ready;
        CData/*0:0*/ top__DOT__u_dispatcher__DOT__task_valid;
        CData/*7:0*/ top__DOT__u_dispatcher__DOT__task_row_id;
        CData/*7:0*/ top__DOT__u_dispatcher__DOT__task_prefix_id;
        CData/*0:0*/ top__DOT__u_dispatcher__DOT__prev_compute_busy;
        CData/*0:0*/ top__DOT__u_dispatcher__DOT__pruner_done;
        CData/*0:0*/ top__DOT__u_dispatcher__DOT__tile_done;
        CData/*7:0*/ top__DOT__u_dispatcher__DOT__temp_pc;
        CData/*7:0*/ top__DOT__u_dispatcher__DOT__temp_row;
        CData/*2:0*/ top__DOT__u_dispatcher__DOT__state;
        CData/*2:0*/ top__DOT__u_dispatcher__DOT__next_state;
        CData/*0:0*/ top__DOT__u_dispatcher__DOT__last_row_seen;
        CData/*0:0*/ top__DOT__u_dispatcher__DOT__collect_timeout;
        CData/*1:0*/ top__DOT__u_dispatcher__DOT__sort_stage;
        CData/*7:0*/ top__DOT__u_dispatcher__DOT__sort_temp_pc;
        CData/*7:0*/ top__DOT__u_dispatcher__DOT__sort_temp_row;
        CData/*7:0*/ top__DOT__u_dispatcher__DOT__current_row;
        CData/*0:0*/ top__DOT__u_processor__DOT__clk;
        CData/*0:0*/ top__DOT__u_processor__DOT__rst_n;
        CData/*0:0*/ top__DOT__u_processor__DOT__task_valid;
        CData/*0:0*/ top__DOT__u_processor__DOT__task_ready;
        CData/*7:0*/ top__DOT__u_processor__DOT__task_row_id;
        CData/*7:0*/ top__DOT__u_processor__DOT__task_prefix_id;
        CData/*3:0*/ top__DOT__u_processor__DOT__weight_addr;
        CData/*0:0*/ top__DOT__u_processor__DOT__weight_rd_en;
        CData/*7:0*/ top__DOT__u_processor__DOT__output_rd_addr;
        CData/*7:0*/ top__DOT__u_processor__DOT__output_wr_addr;
        CData/*0:0*/ top__DOT__u_processor__DOT__output_wr_en;
        CData/*0:0*/ top__DOT__u_processor__DOT__proc_busy;
        CData/*0:0*/ top__DOT__u_processor__DOT__proc_done;
        CData/*2:0*/ top__DOT__u_processor__DOT__state;
    };
    struct {
        CData/*2:0*/ top__DOT__u_processor__DOT__next_state;
        CData/*7:0*/ top__DOT__u_processor__DOT__current_row_id;
        CData/*7:0*/ top__DOT__u_processor__DOT__current_prefix_id;
        CData/*0:0*/ top__DOT__u_processor__DOT__pe_accumulate_en;
        CData/*3:0*/ top__DOT__u_processor__DOT__current_spike_idx;
        CData/*0:0*/ top__DOT__u_processor__DOT__spike_valid;
        CData/*0:0*/ top__DOT__u_processor__DOT__pattern_empty;
        CData/*0:0*/ top__DOT__u_processor__DOT__prefix_loaded;
        CData/*0:0*/ top__DOT__u_processor__DOT__writeback_en;
        CData/*7:0*/ __VdlyDim0__top__DOT__u_pruner__DOT__spike_matrix__v0;
        CData/*0:0*/ __VdlySet__top__DOT__u_pruner__DOT__spike_matrix__v0;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__rst_n__0;
        CData/*0:0*/ __VactContinue;
        VL_IN16(tile_mem_data_in,15,0);
        VL_OUT16(tile_mem_data_out,15,0);
        VL_OUT16(task_pattern,15,0);
        SData/*15:0*/ top__DOT__tile_mem_data_in;
        SData/*15:0*/ top__DOT__tile_mem_data_out;
        SData/*15:0*/ top__DOT__task_pattern;
        SData/*15:0*/ top__DOT____Vcellinp__u_detector__query_pattern;
        SData/*15:0*/ top__DOT__prn_pattern;
        SData/*15:0*/ top__DOT__pattern_r;
        SData/*15:0*/ top__DOT__best_prefix_pattern;
        SData/*15:0*/ top__DOT__output_pattern;
        SData/*15:0*/ top__DOT__u_detector__DOT__query_pattern;
        SData/*15:0*/ top__DOT__u_detector__DOT__tile_mem_data_in;
        SData/*15:0*/ top__DOT__u_detector__DOT__query_reg;
        SData/*15:0*/ top__DOT__u_detector__DOT__tcam_key;
        SData/*15:0*/ top__DOT__u_detector__DOT__tcam_xmask;
        SData/*15:0*/ top__DOT__u_detector__DOT__tile_mem_data_out;
        SData/*15:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__set_key;
        SData/*15:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__set_xmask;
        SData/*15:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__req_key;
        SData/*15:0*/ top__DOT__u_pruner__DOT__pattern;
        SData/*15:0*/ top__DOT__u_pruner__DOT__mem_spike_in;
        SData/*15:0*/ top__DOT__u_pruner__DOT__mem_spike_out;
        SData/*8:0*/ top__DOT__u_pruner__DOT__row_counter;
        SData/*15:0*/ top__DOT__u_pruner__DOT__cur_spikes_r;
        SData/*15:0*/ top__DOT__u_pruner__DOT__pre_spikes_r;
        SData/*15:0*/ top__DOT__u_pruner__DOT__st0_row_spikes;
        SData/*15:0*/ top__DOT__u_pruner__DOT__st1_row_spikes;
        SData/*15:0*/ top__DOT__u_pruner__DOT__st1_pre_spikes;
        SData/*15:0*/ top__DOT__u_pruner__DOT__st2_pattern;
        SData/*15:0*/ top__DOT__u_pruner__DOT__best_spikes_comb;
        SData/*8:0*/ top__DOT__u_pruner__DOT__out_count;
        SData/*15:0*/ top__DOT__u_dispatcher__DOT__row_pattern;
        SData/*15:0*/ top__DOT__u_dispatcher__DOT__task_pattern;
        SData/*8:0*/ top__DOT__u_dispatcher__DOT__collect_count;
        SData/*8:0*/ top__DOT__u_dispatcher__DOT__dispatch_count;
        SData/*8:0*/ top__DOT__u_dispatcher__DOT__sort_count;
        SData/*15:0*/ top__DOT__u_dispatcher__DOT__timeout_counter;
        SData/*15:0*/ top__DOT__u_processor__DOT__task_pattern;
        SData/*15:0*/ top__DOT__u_processor__DOT__current_pattern;
        SData/*15:0*/ top__DOT__u_processor__DOT__pattern_working;
        SData/*15:0*/ __VdlyVal__top__DOT__u_pruner__DOT__spike_matrix__v0;
        VL_INW(weight_data,1023,0,32);
        VL_INW(output_rd_data,2047,0,64);
        VL_OUTW(output_wr_data,2047,0,64);
        VlWide<32>/*1023:0*/ top__DOT__weight_data;
        VlWide<64>/*2047:0*/ top__DOT__output_rd_data;
        VlWide<64>/*2047:0*/ top__DOT__output_wr_data;
    };
    struct {
        VlWide<8>/*255:0*/ top__DOT__det_si_vec;
        VlWide<8>/*255:0*/ top__DOT__valid_mask;
        IData/*31:0*/ top__DOT__k;
        IData/*31:0*/ top__DOT__popcnt16__Vstatic__i;
        VlWide<8>/*255:0*/ top__DOT__u_detector__DOT__si_vec;
        IData/*31:0*/ top__DOT__u_detector__DOT__popcount_loop_idx;
        VlWide<8>/*255:0*/ top__DOT__u_detector__DOT__tcam_matches;
        VlWide<8>/*255:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__line_match;
        VlWide<8>/*255:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__active;
        VlWide<8>/*255:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__match;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__i;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__0__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__1__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__2__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__3__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__4__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__5__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__6__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__7__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__8__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__9__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__10__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__11__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__12__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__13__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__14__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__15__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__16__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__17__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__18__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__19__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__20__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__21__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__22__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__23__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__24__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__25__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__26__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__27__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__28__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__29__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__30__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__31__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__32__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__33__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__34__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__35__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__36__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__37__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__38__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__39__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__40__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__41__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__42__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__43__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__44__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__45__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__46__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__47__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__48__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__49__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__50__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__51__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__52__KET____DOT__mem_tmp;
    };
    struct {
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__53__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__54__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__55__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__56__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__57__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__58__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__59__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__60__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__61__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__62__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__63__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__64__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__65__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__66__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__67__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__68__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__69__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__70__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__71__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__72__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__73__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__74__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__75__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__76__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__77__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__78__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__79__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__80__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__81__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__82__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__83__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__84__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__85__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__86__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__87__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__88__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__89__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__90__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__91__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__92__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__93__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__94__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__95__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__96__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__97__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__98__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__99__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__100__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__101__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__102__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__103__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__104__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__105__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__106__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__107__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__108__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__109__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__110__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__111__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__112__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__113__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__114__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__115__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__116__KET____DOT__mem_tmp;
    };
    struct {
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__117__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__118__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__119__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__120__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__121__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__122__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__123__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__124__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__125__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__126__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__127__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__128__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__129__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__130__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__131__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__132__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__133__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__134__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__135__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__136__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__137__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__138__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__139__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__140__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__141__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__142__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__143__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__144__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__145__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__146__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__147__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__148__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__149__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__150__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__151__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__152__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__153__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__154__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__155__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__156__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__157__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__158__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__159__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__160__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__161__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__162__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__163__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__164__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__165__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__166__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__167__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__168__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__169__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__170__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__171__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__172__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__173__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__174__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__175__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__176__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__177__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__178__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__179__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__180__KET____DOT__mem_tmp;
    };
    struct {
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__181__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__182__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__183__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__184__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__185__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__186__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__187__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__188__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__189__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__190__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__191__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__192__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__193__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__194__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__195__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__196__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__197__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__198__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__199__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__200__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__201__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__202__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__203__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__204__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__205__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__206__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__207__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__208__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__209__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__210__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__211__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__212__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__213__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__214__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__215__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__216__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__217__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__218__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__219__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__220__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__221__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__222__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__223__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__224__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__225__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__226__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__227__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__228__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__229__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__230__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__231__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__232__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__233__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__234__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__235__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__236__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__237__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__238__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__239__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__240__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__241__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__242__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__243__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__244__KET____DOT__mem_tmp;
    };
    struct {
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__245__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__246__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__247__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__248__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__249__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__250__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__251__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__252__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__253__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__254__KET____DOT__mem_tmp;
        IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__genblk1__BRA__255__KET____DOT__mem_tmp;
        VlWide<8>/*255:0*/ top__DOT__u_pruner__DOT__si_vector;
        VlWide<8>/*255:0*/ top__DOT__u_pruner__DOT__si_vec_r;
        VlWide<8>/*255:0*/ top__DOT__u_pruner__DOT__valid_mask;
        VlWide<8>/*255:0*/ top__DOT__u_pruner__DOT__cand_mask_r;
        IData/*31:0*/ top__DOT__u_pruner__DOT__i;
        VlWide<8>/*255:0*/ top__DOT__u_pruner__DOT__st0_si_vec;
        IData/*31:0*/ top__DOT__u_pruner__DOT__j;
        IData/*31:0*/ top__DOT__u_dispatcher__DOT__i;
        IData/*31:0*/ top__DOT__u_dispatcher__DOT__j;
        IData/*31:0*/ top__DOT__u_dispatcher__DOT__min_idx_found;
        IData/*31:0*/ top__DOT__u_dispatcher__DOT__min_pc_found;
        IData/*31:0*/ top__DOT__u_dispatcher__DOT__min_row_found;
        VlWide<32>/*1023:0*/ top__DOT__u_processor__DOT__weight_data;
        VlWide<64>/*2047:0*/ top__DOT__u_processor__DOT__output_rd_data;
        VlWide<64>/*2047:0*/ top__DOT__u_processor__DOT__output_wr_data;
        VlWide<64>/*2047:0*/ top__DOT__u_processor__DOT__prefix_result;
        IData/*31:0*/ top__DOT__u_processor__DOT__bit_idx;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<SData/*15:0*/, 256> top__DOT__tile_ram;
        VlUnpacked<CData/*7:0*/, 256> top__DOT__popcount_ram;
        VlUnpacked<SData/*15:0*/, 256> top__DOT__u_detector__DOT__tile_buffer;
        VlUnpacked<CData/*7:0*/, 256> top__DOT__u_detector__DOT__row_popcounts;
        VlUnpacked<IData/*31:0*/, 256> top__DOT__u_detector__DOT__tcam_core__DOT__mem;
        VlUnpacked<SData/*15:0*/, 256> top__DOT__u_detector__DOT__tcam_core__DOT__key;
        VlUnpacked<SData/*15:0*/, 256> top__DOT__u_detector__DOT__tcam_core__DOT__xmask;
        VlUnpacked<CData/*7:0*/, 256> top__DOT__u_pruner__DOT__NO_table;
        VlUnpacked<SData/*15:0*/, 256> top__DOT__u_pruner__DOT__spike_matrix;
        VlUnpacked<CData/*7:0*/, 128> top__DOT__u_pruner__DOT__best_idx_lvl0;
        VlUnpacked<CData/*7:0*/, 128> top__DOT__u_pruner__DOT__best_NO_lvl0;
        VlUnpacked<CData/*7:0*/, 64> top__DOT__u_pruner__DOT__best_idx_lvl1;
        VlUnpacked<CData/*7:0*/, 64> top__DOT__u_pruner__DOT__best_NO_lvl1;
        VlUnpacked<CData/*7:0*/, 32> top__DOT__u_pruner__DOT__best_idx_lvl2;
        VlUnpacked<CData/*7:0*/, 32> top__DOT__u_pruner__DOT__best_NO_lvl2;
        VlUnpacked<CData/*0:0*/, 256> top__DOT__u_pruner__DOT____VdfgBinToOneHot_Tab_he920b6b0_0_0;
        VlUnpacked<CData/*7:0*/, 256> top__DOT__u_dispatcher__DOT__pst_prefix_id;
        VlUnpacked<SData/*15:0*/, 256> top__DOT__u_dispatcher__DOT__pst_pattern;
        VlUnpacked<CData/*7:0*/, 256> top__DOT__u_dispatcher__DOT__pst_popcnt;
        VlUnpacked<CData/*7:0*/, 256> top__DOT__u_dispatcher__DOT__pst_row_id;
        VlUnpacked<CData/*0:0*/, 256> top__DOT__u_dispatcher__DOT__pst_valid;
        VlUnpacked<CData/*7:0*/, 256> top__DOT__u_dispatcher__DOT__sort_row_id;
        VlUnpacked<CData/*7:0*/, 256> top__DOT__u_dispatcher__DOT__sort_popcnt;
        VlUnpacked<CData/*7:0*/, 256> top__DOT__u_dispatcher__DOT__collected_rows;
        VlUnpacked<SData/*15:0*/, 128> top__DOT__u_processor__DOT__pe_partial_sum;
        VlUnpacked<CData/*7:0*/, 128> top__DOT__u_processor__DOT__pe_weight;
    };
    VlNBACommitQueue<VlUnpacked<IData/*31:0*/, 256>, false, IData/*31:0*/, 1> __VdlyCommitQueuetop__DOT__u_detector__DOT__tcam_core__DOT__mem;
    VlNBACommitQueue<VlUnpacked<CData/*7:0*/, 256>, false, CData/*7:0*/, 1> __VdlyCommitQueuetop__DOT__u_dispatcher__DOT__sort_popcnt;
    VlNBACommitQueue<VlUnpacked<CData/*7:0*/, 256>, false, CData/*7:0*/, 1> __VdlyCommitQueuetop__DOT__u_dispatcher__DOT__sort_row_id;
    VlNBACommitQueue<VlUnpacked<CData/*0:0*/, 256>, false, CData/*0:0*/, 1> __VdlyCommitQueuetop__DOT__u_dispatcher__DOT__pst_valid;
    VlNBACommitQueue<VlUnpacked<CData/*7:0*/, 256>, false, CData/*7:0*/, 1> __VdlyCommitQueuetop__DOT__u_dispatcher__DOT__collected_rows;
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<2> __VactTriggered;
    VlTriggerVec<2> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr CData/*2:0*/ top__DOT__ST_IDLE = 0U;
    static constexpr CData/*2:0*/ top__DOT__ST_LOAD = 1U;
    static constexpr CData/*2:0*/ top__DOT__ST_INIT = 2U;
    static constexpr CData/*2:0*/ top__DOT__ST_PROCESS = 3U;
    static constexpr CData/*2:0*/ top__DOT__ST_DONE = 4U;
    static constexpr CData/*1:0*/ top__DOT__u_detector__DOT__ST_IDLE = 0U;
    static constexpr CData/*1:0*/ top__DOT__u_detector__DOT__ST_LOAD = 1U;
    static constexpr CData/*1:0*/ top__DOT__u_detector__DOT__ST_QUERY = 2U;
    static constexpr CData/*1:0*/ top__DOT__u_detector__DOT__ST_POPCOUNT = 3U;
    static constexpr CData/*2:0*/ top__DOT__u_pruner__DOT__S_IDLE = 0U;
    static constexpr CData/*2:0*/ top__DOT__u_pruner__DOT__S_FILT = 1U;
    static constexpr CData/*2:0*/ top__DOT__u_pruner__DOT__S_SEL = 2U;
    static constexpr CData/*2:0*/ top__DOT__u_pruner__DOT__S_XOR = 3U;
    static constexpr CData/*2:0*/ top__DOT__u_pruner__DOT__S_OUT = 4U;
    static constexpr CData/*2:0*/ top__DOT__u_pruner__DOT__S_NEXT = 5U;
    static constexpr CData/*2:0*/ top__DOT__u_dispatcher__DOT__S_IDLE = 0U;
    static constexpr CData/*2:0*/ top__DOT__u_dispatcher__DOT__S_COLLECT = 1U;
    static constexpr CData/*2:0*/ top__DOT__u_dispatcher__DOT__S_SORT = 2U;
    static constexpr CData/*2:0*/ top__DOT__u_dispatcher__DOT__S_DISPATCH = 3U;
    static constexpr CData/*2:0*/ top__DOT__u_dispatcher__DOT__S_DONE = 4U;
    static constexpr CData/*2:0*/ top__DOT__u_processor__DOT__ST_IDLE = 0U;
    static constexpr CData/*2:0*/ top__DOT__u_processor__DOT__ST_LOAD_PFX = 1U;
    static constexpr CData/*2:0*/ top__DOT__u_processor__DOT__ST_DECODE = 2U;
    static constexpr CData/*2:0*/ top__DOT__u_processor__DOT__ST_ACCUMULATE = 3U;
    static constexpr CData/*2:0*/ top__DOT__u_processor__DOT__ST_WRITEBACK = 4U;
    static constexpr IData/*31:0*/ top__DOT__ROWS = 0x00000100U;
    static constexpr IData/*31:0*/ top__DOT__SPIKES = 0x00000010U;
    static constexpr IData/*31:0*/ top__DOT__NO_WIDTH = 8U;
    static constexpr IData/*31:0*/ top__DOT__PE_COUNT = 0x00000080U;
    static constexpr IData/*31:0*/ top__DOT__WEIGHT_WIDTH = 8U;
    static constexpr IData/*31:0*/ top__DOT__ACC_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ top__DOT__u_detector__DOT__SPIKES = 0x00000010U;
    static constexpr IData/*31:0*/ top__DOT__u_detector__DOT__ROWS = 0x00000100U;
    static constexpr IData/*31:0*/ top__DOT__u_detector__DOT__NO_WIDTH = 8U;
    static constexpr IData/*31:0*/ top__DOT__u_detector__DOT__TEST_ROWS = 0x00000100U;
    static constexpr IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__ADDR_WIDTH = 8U;
    static constexpr IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__KEY_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__MASK_DISABLE = 0U;
    static constexpr IData/*31:0*/ top__DOT__u_detector__DOT__tcam_core__DOT__MEM_WIDTH = 0x00000020U;
    static constexpr IData/*31:0*/ top__DOT__u_pruner__DOT__N = 0x00000100U;
    static constexpr IData/*31:0*/ top__DOT__u_pruner__DOT__M = 0x00000010U;
    static constexpr IData/*31:0*/ top__DOT__u_pruner__DOT__NO_WIDTH = 8U;
    static constexpr IData/*31:0*/ top__DOT__u_dispatcher__DOT__ROWS = 0x00000100U;
    static constexpr IData/*31:0*/ top__DOT__u_dispatcher__DOT__SPIKES = 0x00000010U;
    static constexpr IData/*31:0*/ top__DOT__u_dispatcher__DOT__PATTERN_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ top__DOT__u_dispatcher__DOT__NO_WIDTH = 8U;
    static constexpr IData/*31:0*/ top__DOT__u_dispatcher__DOT__IDX_W = 8U;
    static constexpr IData/*31:0*/ top__DOT__u_processor__DOT__ROWS = 0x00000100U;
    static constexpr IData/*31:0*/ top__DOT__u_processor__DOT__SPIKES = 0x00000010U;
    static constexpr IData/*31:0*/ top__DOT__u_processor__DOT__PE_COUNT = 0x00000080U;
    static constexpr IData/*31:0*/ top__DOT__u_processor__DOT__WEIGHT_WIDTH = 8U;
    static constexpr IData/*31:0*/ top__DOT__u_processor__DOT__ACC_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ top__DOT__u_processor__DOT__NO_WIDTH = 8U;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
