// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vtop.h for the primary calling header

#ifndef VERILATED_VTOP___024ROOT_H_
#define VERILATED_VTOP___024ROOT_H_  // guard

#include "verilated.h"


class Vtop__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vtop___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(clk,0,0);
        VL_IN8(rst,0,0);
        VL_IN8(q_valid,0,0);
        VL_OUT8(q_ready,0,0);
        VL_OUT8(si_valid,0,0);
        VL_OUT8(det_done,0,0);
        VL_IN8(row_idx,7,0);
        VL_OUT8(row_popcnt,7,0);
        VL_OUT8(detector_init_done,0,0);
        VL_IN8(tile_mem_addr,7,0);
        VL_IN8(tile_mem_wr_en,0,0);
        VL_IN8(popcount_mem_addr,7,0);
        VL_IN8(popcount_mem_data_in,7,0);
        VL_IN8(popcount_mem_wr_en,0,0);
        CData/*0:0*/ detector__DOT__clk;
        CData/*0:0*/ detector__DOT__rst;
        CData/*0:0*/ detector__DOT__q_valid;
        CData/*0:0*/ detector__DOT__q_ready;
        CData/*0:0*/ detector__DOT__si_valid;
        CData/*0:0*/ detector__DOT__det_done;
        CData/*7:0*/ detector__DOT__row_idx;
        CData/*7:0*/ detector__DOT__row_popcnt;
        CData/*0:0*/ detector__DOT__detector_init_done;
        CData/*7:0*/ detector__DOT__tile_mem_addr;
        CData/*0:0*/ detector__DOT__tile_mem_wr_en;
        CData/*7:0*/ detector__DOT__popcount_mem_addr;
        CData/*7:0*/ detector__DOT__popcount_mem_data_in;
        CData/*0:0*/ detector__DOT__popcount_mem_wr_en;
        CData/*0:0*/ detector__DOT__popcounts_calculated;
        CData/*1:0*/ detector__DOT__state;
        CData/*1:0*/ detector__DOT__next_state;
        CData/*7:0*/ detector__DOT__load_counter;
        CData/*7:0*/ detector__DOT__popcount_counter;
        CData/*0:0*/ detector__DOT__initialized;
        CData/*0:0*/ detector__DOT__q_valid_d1;
        CData/*0:0*/ detector__DOT__q_valid_d2;
        CData/*7:0*/ detector__DOT__row_popcnt_stage1;
        CData/*7:0*/ detector__DOT__row_popcnt_stage2;
        CData/*7:0*/ detector__DOT__tcam_addr;
        CData/*0:0*/ detector__DOT__tcam_set_valid;
        CData/*0:0*/ detector__DOT__tcam_set_clr;
        CData/*0:0*/ detector__DOT__tcam_req_valid;
        CData/*7:0*/ detector__DOT__popcount_mem_data_out;
        CData/*0:0*/ detector__DOT__tcam_core__DOT__clk;
        CData/*0:0*/ detector__DOT__tcam_core__DOT__rst;
        CData/*7:0*/ detector__DOT__tcam_core__DOT__set_addr;
        CData/*0:0*/ detector__DOT__tcam_core__DOT__set_clr;
        CData/*0:0*/ detector__DOT__tcam_core__DOT__set_valid;
        CData/*0:0*/ detector__DOT__tcam_core__DOT__req_valid;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__clk__0;
        CData/*0:0*/ __VactContinue;
        VL_IN16(query_pattern,15,0);
        VL_IN16(tile_mem_data_in,15,0);
        SData/*15:0*/ detector__DOT__query_pattern;
        SData/*15:0*/ detector__DOT__tile_mem_data_in;
        SData/*15:0*/ detector__DOT__query_reg;
        SData/*15:0*/ detector__DOT__tcam_key;
        SData/*15:0*/ detector__DOT__tcam_xmask;
        SData/*15:0*/ detector__DOT__tile_mem_data_out;
        SData/*15:0*/ detector__DOT__tcam_core__DOT__set_key;
        SData/*15:0*/ detector__DOT__tcam_core__DOT__set_xmask;
        SData/*15:0*/ detector__DOT__tcam_core__DOT__req_key;
    };
    struct {
        VL_OUTW(si_vec,255,0,8);
        VlWide<8>/*255:0*/ detector__DOT__si_vec;
        IData/*31:0*/ detector__DOT__popcount_loop_idx;
        VlWide<8>/*255:0*/ detector__DOT__match_d1;
        VlWide<8>/*255:0*/ detector__DOT__match_d2;
        VlWide<8>/*255:0*/ detector__DOT__tcam_matches;
        IData/*31:0*/ detector__DOT__calc_popcount__Vstatic__i;
        VlWide<8>/*255:0*/ detector__DOT__tcam_core__DOT__line_match;
        VlWide<8>/*255:0*/ detector__DOT__tcam_core__DOT__active;
        VlWide<8>/*255:0*/ detector__DOT__tcam_core__DOT__match;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__i;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__0__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__1__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__2__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__3__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__4__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__5__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__6__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__7__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__8__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__9__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__10__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__11__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__12__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__13__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__14__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__15__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__16__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__17__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__18__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__19__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__20__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__21__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__22__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__23__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__24__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__25__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__26__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__27__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__28__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__29__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__30__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__31__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__32__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__33__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__34__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__35__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__36__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__37__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__38__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__39__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__40__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__41__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__42__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__43__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__44__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__45__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__46__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__47__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__48__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__49__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__50__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__51__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__52__KET____DOT__mem_tmp;
    };
    struct {
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__53__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__54__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__55__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__56__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__57__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__58__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__59__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__60__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__61__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__62__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__63__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__64__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__65__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__66__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__67__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__68__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__69__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__70__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__71__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__72__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__73__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__74__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__75__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__76__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__77__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__78__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__79__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__80__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__81__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__82__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__83__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__84__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__85__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__86__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__87__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__88__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__89__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__90__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__91__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__92__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__93__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__94__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__95__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__96__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__97__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__98__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__99__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__100__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__101__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__102__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__103__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__104__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__105__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__106__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__107__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__108__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__109__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__110__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__111__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__112__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__113__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__114__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__115__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__116__KET____DOT__mem_tmp;
    };
    struct {
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__117__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__118__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__119__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__120__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__121__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__122__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__123__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__124__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__125__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__126__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__127__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__128__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__129__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__130__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__131__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__132__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__133__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__134__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__135__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__136__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__137__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__138__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__139__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__140__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__141__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__142__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__143__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__144__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__145__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__146__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__147__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__148__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__149__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__150__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__151__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__152__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__153__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__154__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__155__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__156__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__157__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__158__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__159__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__160__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__161__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__162__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__163__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__164__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__165__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__166__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__167__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__168__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__169__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__170__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__171__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__172__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__173__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__174__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__175__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__176__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__177__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__178__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__179__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__180__KET____DOT__mem_tmp;
    };
    struct {
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__181__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__182__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__183__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__184__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__185__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__186__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__187__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__188__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__189__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__190__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__191__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__192__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__193__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__194__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__195__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__196__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__197__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__198__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__199__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__200__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__201__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__202__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__203__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__204__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__205__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__206__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__207__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__208__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__209__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__210__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__211__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__212__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__213__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__214__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__215__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__216__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__217__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__218__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__219__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__220__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__221__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__222__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__223__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__224__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__225__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__226__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__227__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__228__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__229__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__230__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__231__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__232__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__233__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__234__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__235__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__236__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__237__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__238__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__239__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__240__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__241__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__242__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__243__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__244__KET____DOT__mem_tmp;
    };
    struct {
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__245__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__246__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__247__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__248__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__249__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__250__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__251__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__252__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__253__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__254__KET____DOT__mem_tmp;
        IData/*31:0*/ detector__DOT__tcam_core__DOT__genblk1__BRA__255__KET____DOT__mem_tmp;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<SData/*15:0*/, 256> detector__DOT__tile_buffer;
        VlUnpacked<CData/*7:0*/, 256> detector__DOT__row_popcounts;
        VlUnpacked<CData/*7:0*/, 8> detector__DOT__calc_popcount__Vstatic__stage1;
        VlUnpacked<CData/*7:0*/, 4> detector__DOT__calc_popcount__Vstatic__stage2;
        VlUnpacked<CData/*7:0*/, 2> detector__DOT__calc_popcount__Vstatic__stage3;
        VlUnpacked<CData/*7:0*/, 1> detector__DOT__calc_popcount__Vstatic__stage4;
        VlUnpacked<IData/*31:0*/, 256> detector__DOT__tcam_core__DOT__mem;
        VlUnpacked<SData/*15:0*/, 256> detector__DOT__tcam_core__DOT__key;
        VlUnpacked<SData/*15:0*/, 256> detector__DOT__tcam_core__DOT__xmask;
    };
    VlNBACommitQueue<VlUnpacked<IData/*31:0*/, 256>, false, IData/*31:0*/, 1> __VdlyCommitQueuedetector__DOT__tcam_core__DOT__mem;
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<1> __VicoTriggered;
    VlTriggerVec<1> __VactTriggered;
    VlTriggerVec<1> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vtop__Syms* const vlSymsp;

    // PARAMETERS
    static constexpr CData/*1:0*/ detector__DOT__ST_IDLE = 0U;
    static constexpr CData/*1:0*/ detector__DOT__ST_LOAD = 1U;
    static constexpr CData/*1:0*/ detector__DOT__ST_QUERY = 2U;
    static constexpr CData/*1:0*/ detector__DOT__ST_POPCOUNT = 3U;
    static constexpr IData/*31:0*/ detector__DOT__SPIKES = 0x00000010U;
    static constexpr IData/*31:0*/ detector__DOT__ROWS = 0x00000100U;
    static constexpr IData/*31:0*/ detector__DOT__NO_WIDTH = 8U;
    static constexpr IData/*31:0*/ detector__DOT__TEST_ROWS = 0x00000100U;
    static constexpr IData/*31:0*/ detector__DOT__tcam_core__DOT__ADDR_WIDTH = 8U;
    static constexpr IData/*31:0*/ detector__DOT__tcam_core__DOT__KEY_WIDTH = 0x00000010U;
    static constexpr IData/*31:0*/ detector__DOT__tcam_core__DOT__MASK_DISABLE = 0U;
    static constexpr IData/*31:0*/ detector__DOT__tcam_core__DOT__MEM_WIDTH = 0x00000020U;

    // CONSTRUCTORS
    Vtop___024root(Vtop__Syms* symsp, const char* v__name);
    ~Vtop___024root();
    VL_UNCOPYABLE(Vtop___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
